- ldclient-rb.gemspec
Having the home page point to github will give users better information about the gem.
> Update the gem's homepage to point to github instead

- lib/ldclient-rb/ldclient.rb
- spec/ldclient_spec.rb
`@queue` itself may be threadsafe, but the code that flushes it may not be, since it will only pop off a number of elements in a past amount of time.
> Make sure flushing the client queue flushes the entire queue

- lib/ldclient-rb/stream.rb
Disconnects from the stream API are normal behavior. Reduce logging level around stream issues to reflect this.
> Reduce logging level for stream issues

- ldclient-rb.gemspec
Sidekiq recently released an upgrade and moved from celluoid to concurrent-ruby 1.x. This PR bumps the version of concurrent-ruby to 1.0.0.
> Bump concurrent-ruby to 1.0.0

- lib/ldclient-rb/ldclient.rb
I discovered that when a feature is off in the UI the gem will return nil instead of the default. Looking in the code I see there is a check for it but it never gets assigned to the `value` variable.
> Check for nil never sets the value to default

- lib/ldclient-rb.rb
- lib/ldclient-rb/ldclient.rb
- lib/ldclient-rb/settings.rb
- spec/ldclient_spec.rb
Here's a method for managing user flag settings. I thought it might make sense to have in a separate module in case you want to treat this API differently from the flag APIs.
> Add update_user_flag_setting method in new Settings module

- lib/ldclient-rb/ldclient.rb
- lib/ldclient-rb/stream.rb
- spec/ldclient_spec.rb
If streaming is enabled, these new methods will not make remote calls
> New methods for fetching all user settings and all feature flags

- ldclient-rb.gemspec
- lib/ldclient-rb/store.rb
Fixes #61 
Bumping the version caused an issue with LaunchDarkly::ThreadSafeMemoryStore not implementing a delete method.
Implemented the delete method - tests pass.
UAT'ed the gem locally for using feature toggles and the toggle? method. Haven't done any further testing in that regard.
Running the gem in production now without further issues.
> Bump faraday-http-cache version

- ldclient-rb.gemspec
- lib/ldclient-rb/stream.rb
- spec/stream_spec.rb
This eliminates our dependency on EventMachine and replaces it with a Celluloid-based library for EventSource
> Switch to celluloid-based eventsource implementation

- README.md
Per https://github.com/launchdarkly/ruby-client/blob/master/lib/ldclient-rb/ldclient.rb#L59, the preferred way to test a feature flag is to use `variation(key, user, default)`, not `toggle?(key, user, default)`
> Rename toggle? to variation

- ldclient-rb.gemspec
- lib/ldclient-rb/config.rb
- lib/ldclient-rb/requestor.rb
- lib/ldclient-rb/stream.rb
Update to sse client with heartbeat detection + exponential backoff. Add more logging.
> Update to sse client with heartbeat detection + exponential backoff

- ldclient-rb.gemspec
- lib/ldclient-rb/config.rb
- lib/ldclient-rb/requestor.rb
- lib/ldclient-rb/stream.rb
- spec/requestor_spec.rb
Adds proxy support to the ruby sdk.
The new configuration option is as follows:
```rb
{ :proxy => "protocol://url:port" }
```
With this change:
1) HTTP Proxies are configurable via the above parameter.
2) HTTP Proxies are also configurable via the `HTTP_PROXY` and `http_proxy` environment variables.
> Add http proxy support

- ldclient-rb.gemspec
- lib/ldclient-rb/evaluation.rb
- spec/evaluation_spec.rb
- Adds support for a future LaunchDarkly feature, coming soon: semantic version user attributes.
- It is now possible to compute rollouts based on an integer attribute of a user, not just a string attribute.
> release 2.5.0

- lib/ldclient-rb/evaluation.rb
- lib/ldclient-rb/events.rb
- lib/ldclient-rb/ldclient.rb
- lib/ldclient-rb/polling.rb
- lib/ldclient-rb/redis_store.rb
- lib/ldclient-rb/requestor.rb
- lib/ldclient-rb/stream.rb
When blocks are used, and the set logging
level of the Logger object is above that of
the call, the block will not be executed.
This prevents string allocations in log
messages that would not be retained anyway,
which can be especially significant when
calling `inspect` on large-ish objects.
For rationale, see http://hawkins.io/2013/08/using-the-ruby-logger/
and https://stackoverflow.com/questions/30144317
> Use Logger block form calls

- README.md
- lib/ldclient-rb/redis_store.rb
- spec/redis_feature_store_spec.rb
- In the Redis feature store, fixed a synchronization problem that could cause a feature flag update to be missed if several of them happened in rapid succession.
> prepare 3.0.3 release

- .circleci/config.yml
- README.md
- ldclient-rb.gemspec
- lib/ldclient-rb.rb
- lib/ldclient-rb/events.rb
- lib/ldclient-rb/ldclient.rb
- lib/ldclient-rb/polling.rb
- lib/ldclient-rb/requestor.rb
- lib/ldclient-rb/stream.rb
- lib/ldclient-rb/user_filter.rb
- lib/ldclient-rb/util.rb
- lib/sse_client.rb
- lib/sse_client/backoff.rb
- lib/sse_client/sse_client.rb
- lib/sse_client/sse_events.rb
- lib/sse_client/streaming_http.rb
- spec/events_spec.rb
- spec/ldclient_spec.rb
- spec/polling_spec.rb
- spec/sse_client/sse_client_spec.rb
- spec/sse_client/sse_events_spec.rb
- spec/sse_client/sse_shared.rb
- spec/sse_client/streaming_http_spec.rb
- The client no longer uses Celluloid for streaming I/O. Instead, it uses [socketry](https://github.com/socketry/socketry).
- The client now treats most HTTP 4xx errors as unrecoverable: that is, after receiving such an error, it will not make any more HTTP requests for the lifetime of the client instance, in effect taking the client offline. This is because such errors indicate either a configuration problem (invalid SDK key) or a bug, which is not likely to resolve without a restart or an upgrade. This does not apply if the error is 400, 408, 429, or any 5xx error.
- During initialization, if the client receives any of the unrecoverable errors described above, the client constructor will return immediately; previously it would continue waiting until a timeout. The `initialized?` method …
> prepare 5.0.0 release

- lib/sse_client/sse_client.rb
- lib/sse_client/streaming_http.rb
- spec/sse_client/sse_client_spec.rb
Fixed a regression in version 5.0.0 that could prevent the client from reconnecting if the stream connection was dropped by the server.
> prepare 5.0.1 release

- lib/ldclient-rb/file_data_source.rb
`LoadError` is not a `StandardError` and therefore is not caught by a bare `rescue` block.
> rescue LoadError explicitly

- lib/launchdarkly-server-sdk.rb
- spec/launchdarkly-server-sdk_spec.rb
- spec/launchdarkly-server-sdk_spec_autoloadtest.rb
I gotta say, it's not ideal that this repo, the gem name, and the require statement are all different. Currently, we have to do one of the following to load the gem:
```ruby
gem "launchdarkly-server-sdk"
Bundler.require(:development)
LaunchDarkly::LDClient  # 💣
require "ldclient-rb"   # 😕
LaunchDarkly::LDClient  # ✅
```
```ruby
gem "launchdarkly-server-sdk", require: "ldclient-rb" # 😕
Bundler.require(:development)
LaunchDarkly::LDClient  # ✅
```
But what if there is a better way?...
Bundler can automatically load gems if there is a conventionally named. First, it will try to [load a file matching the name of the gem](https://github.com/bundler/bundler/blob/v1.17.3/lib/bundler/runtime.rb#L76-L87). Then, it will rely on its naming [conventions](https://guides.rubygems.org/name-your-gem/). …
> Add autoloadability via Bundler.require

- lib/ldclient-rb/impl/integrations/redis_impl.rb
- lib/ldclient-rb/integrations/redis.rb
- lib/ldclient-rb/redis_store.rb
- spec/redis_feature_store_spec.rb
I'm not sure how to validate my changes against "all supported platform versions". I assume there is continuous integration that will run specs against all Ruby/RubyGems/Redis/etc. versions, but maybe I'm wrong. It would take hours for me to figure out how to do this locally.
My application needs to tightly control Redis connections because we have very high server concurrency so we need to be able to pass a Redis `ConnectionPool` directly to the SDK rather than having the SDK manage its own pool and have independent connections. However, we also use a preforking web server (Unicorn) and preload our application. Redis connections inside a `ConnectionPool` handle this gracefully, if the socket is shared to a forked child process …
> Only shutdown the Redis pool if it is owned by the SDK

- lib/ldclient-rb/impl/integrations/redis_impl.rb
`redis-rb 4.2.0` introduced the following warning 
```
`Redis#exists(key)` will return an Integer in redis-rb 4.3. `exists?` returns a boolean, you should use it instead. To opt-in to the new behavior now you can set Redis.exists_returns_integer =  true. To disable this message and keep the current (boolean) behaviour of 'exists' you can set `Redis.exists_returns_integer = false`, but this option will be removed in 5.0.
```
I drafted a PR [a few months ago](https://github.com/launchdarkly/ruby-server-sdk/pull/163) but never sat down to complete it, so here it is again.
I think this is the most accurate one, since the warning and the `exists?` [method was introduced in 4.2.2](https://github.com/redis/redis-rb/blob/7587668c1fe5c1f30387d80b5682a93678be40aa/CHANGELOG.md#420)
However, I can …
> Remove warning

- lib/ldclient-rb/ldclient.rb
This PR adds the evaluated key to the error log when the context is invalid to make it easier to track down where we might be passing in an invalid context. Happy to make changes/add a spec if you point me to the right place to add it!
> Add key to error log for invalid context during variation call for easier debugging

- lib/ldclient-rb/config.rb
Fixes default_connect_timeout documentation to match the value returned by the code.
> [docs] Fix default_connect_timeout docs to match actual value.

- .github/actions/publish/action.yml
- CHANGELOG.md
- lib/ldclient-rb/ldclient.rb
- lib/ldclient-rb/version.rb
- release-please-config.json
- spec/ldclient_spec.rb
- ci: Replace releaser with release please (#228)
- fix: Calling stop in ldd mode no longer raises an exception (#235)
> fix: Calling stop in ldd mode no longer raises an exception

- contract-tests/service.rb
- lib/ldclient-rb/events.rb
- spec/events_spec.rb
The v4 event schema is being broadened to accept full context payloads instead of only the context kind/key pairings.
There are several additional commits coming to address the updated spec, so these PRs are going to be merged into a feature branch.
> feat: Inline contexts for all evaluation events

- .github/actions/publish/action.yml
- .github/workflows/manual-publish.yml
- .github/workflows/release-please.yml
- PROVENANCE.md
- README.md
**Related issues**
Provide links to any issues in this repository or elsewhere relating to this pull request.
Using Github SLSA generator to generate build provenance for ruby-server-sdk
Implementation based off of previous SDK SLSA integrations with release-please
**Describe alternatives you've considered**
Provide a clear and concise description of any alternative solutions or features you've considered.
**Additional context**
Add any other context about the pull request here.
> build: adding provenance generation to ruby release-please workflow

- lib/ldclient-rb/config.rb
- spec/config_spec.rb
I did not validate it against all platform versions, but rather than use something like `present?` or `try` or `&.` I just used the ruby idiom for checking nil/false by using the object at the end, like `&& object` 
Have you considered putting that last requirement into the CI's hands so that it might become unnecessary?
**Related issues**
None that I am aware of. 
The code previously checked that Rails responded to `logger` and if it did, assumes there is actually a logger present, which is not always the case. This leaves LD with a `nil` value for `logger` which causes the application to crash. 
**Describe alternatives you've considered**
I did not consider any alternatives. 
**Additional context**
None.
> fix: Do not assume Rails.logger exists simply because it responds to the method

- lib/ldclient-rb/impl/model/feature_flag.rb
- spec/impl/evaluator_prereq_spec.rb
When parsing flag payload information, the SDK attempts to pre-check several failure conditions. One of those conditions was to ensure that a provided prereq has a valid variation index.
However, the system cannot actually perform this check at parse time since the prerequisite flag might not have been parsed yet.
As this check served only as a nice to have, I have removed it and added a test verifying the prereq behavior still operates as expected.
Fixes #260
> fix: Remove invalid prereq `check_variation_range` check

- lib/ldclient-rb/impl/model/feature_flag.rb
- spec/impl/evaluator_prereq_spec.rb
When parsing flag payload information, the SDK attempts to pre-check several failure conditions. One of those conditions was to ensure that a provided prereq has a valid variation index.
However, the system cannot actually perform this check at parse time since the prerequisite flag might not have been parsed yet.
As this check served only as a nice to have, I have removed it and added a test verifying the prereq behavior still operates as expected.
Fixes #260
> fix: Remove invalid prereq `check_variation_range` check (#261)

- .github/workflows/ci.yml
- contract-tests/client_entity.rb
- contract-tests/hook.rb
- contract-tests/service.rb
- lib/ldclient-rb/config.rb
- lib/ldclient-rb/impl/evaluation_with_hook_result.rb
- lib/ldclient-rb/interfaces.rb
- lib/ldclient-rb/ldclient.rb
- spec/ldclient_hooks_spec.rb
- spec/mock_components.rb
The individual work has been reviewed. This is just merging it into main in preparation for the release.
> chore: Merging hooks work into main

- launchdarkly-server-sdk.gemspec
> fix: Add observer as explicit dependency

- lib/ldclient-rb/context.rb
Legacy user format was indeed removed in v8.0.0. However, this
deprecation warning was missed causing confusion for customers.
> fix: Remove outdated deprecation notice

- lib/ldclient-rb/impl/integrations/file_data_source.rb
The file data source allows specifying flag information as a full flag
definition, or as a shorted map of flag key:value mappings.
In the case of the flag values, or in the case of a malformed flag
definition, a flag version might not be specified. When this happens,
users of the flag tracker will notice an error because the version
comparison code will encounter an unexpected nil value.
To prevent this from happening, the file data source should be setting a
version for each flag or segment it reads.
When these items are modified in the LaunchDarkly UI, we automatically
increment the version associated with the item. To make this easier for
the user going forward, the file data source will handle incrementing
this version number each time the file is re-read.
> fix: Increment flag & segment versions when reloading from file data source

- contract-tests/service.rb
- launchdarkly-server-sdk.gemspec
- lib/ldclient-rb/config.rb
- lib/ldclient-rb/impl/util.rb
- lib/ldclient-rb/util.rb
- spec/impl/util_spec.rb
Previously, we were allowing any non-empty string value to be provided
as a payload filter key. However, customers can only create a filter key
with a subset of characters.
In an effort to warn them earlier about potentially invalid
configurations, we are adding some basic key validation work as part of
the start up sequence.
> fix: Add additional payload filter key validation

- lib/ldclient-rb/impl/data_store.rb
- lib/ldclient-rb/in_memory_store.rb
The data stores in the SDK have to deal with multiple types of data --
features (or flags) and segments. These types have long been simple
hashes in our SDK, with one defining an optional lambda property.
With Ruby 3.3 and the introduction of `Process.warmup`, we have seen an
issue where, after warmup, the in memory store needs a `rehash` method
call before these kind constants can be used reliably to access the
store.
To combat this, I am moving these kinds into a class. This class as
explicit hash key behaviors, so theoretically shouldn't have this
problem Local testing has shown this to be the case.
This class is also given a dictionary interface to maintain compliance
with the existing implementation. While people should not be relying on
these constants explicitly, they do flow …
> fix: Modify data kind constants to avoid Process.warmup rehash

- launchdarkly-server-sdk.gemspec
**Related issues**
In #303 I was asked to install the gem in my Gemfile from source to confirm a bug fix but I encountered two `bundle install` errors that prevented that. I had to make these changes to be able to successfully install from source.
Do not depend on rake in the gemspec as there is no need too. Replacing Rake's `FileList` with Ruby's `Dir` is a common use for the affected line and can be seen in many popular gemspecs.
**Describe alternatives you've considered**
I didn't consider any alternatives because it would be best to not depend on an unnecessary dependency (e.g. rake) in the gemspec file. This also follows what is commonly done in other Ruby gems so it's well supported.
> fix: Allow gem to be installed from source

- .github/actions/check/action.yml
- .github/actions/publish-docs/action.yml
- .github/actions/publish/action.yml
- .github/actions/setup/action.yml
- .github/workflows/build-gem.yml
- .github/workflows/ci.yml
- .github/workflows/manual-publish-docs.yml
- .github/workflows/manual-publish.yml
- .github/workflows/release-please.yml
When we originally introduced the zlib dependency, we attempted to
exclude that dependency in jRuby. However, that exclusion is a
build-time check, not run-time as previously though.
To support this, we now publish 2 gems -- the standard gem and the
*-java specific version. The latter of which is now shipped without the
zlib gem requirement.
> fix: Publish java-specific platform gem

- launchdarkly-server-sdk.gemspec
- lib/ldclient-rb/events.rb
- lib/ldclient-rb/impl/big_segments.rb
- lib/ldclient-rb/impl/integrations/file_data_source.rb
- lib/ldclient-rb/impl/migrations/migrator.rb
- lib/ldclient-rb/impl/repeating_task.rb
- lib/ldclient-rb/impl/store_client_wrapper.rb
- lib/ldclient-rb/non_blocking_thread_pool.rb
- lib/ldclient-rb/polling.rb
- spec/impl/repeating_task_spec.rb
**Related issues**
There are no related issues at the time of filing.
At @speedshop we have a client that uses LaunchDarkly. One thing we noticed was that the Ruby SDK relies on the `Thread` very extensively, either directly or through the `concurrent-ruby` gem. As a result of this, a number of threads will be created after the first call to LD:
This is all expected, and normally this is fine. In some specific circumstances where a deep dive into e.g. performance of each thread is required, not having a thread name could possibly lead to a longer investigation. For example, [the `gvl-tracing` gem](https://github.com/ivoanjo/gvl-tracing) generates [Perfetto](https://ui.perfetto.dev/) profiling results for each thread, that looks …
> fix: Provide thread names whenever possible
